### ISSUE TITLE
Preluare coordonate sesizare din exif-ul imaginii

### ISSUE THREAD

**Issue by d-stefan** [alexbulintis/sesizez#11]
În momentul de față coordonatele și adresa adaugată în sesizare sunt preluate din adresa de domiciliu setată, însă nu întotdeauna fac o sesizare în zona unde locuiesc.

Mi-aș dori ca acele coordonate sa fie preluate din imagine și dacă e posibil, datele exif să fie șterse înainte de adăugarea în email, similar cu funcționalitatea https://gitlab.com/juanitobananas/scrambled-exif.

**Comment by alexbulintis** [comment]
I love it!

Momentan adresa adăugată in sesizare este cea in care te afli in care o faci (cu ideea că vezi ceva in neregulă, faci o poză și o trimiți imediat)

Însă aș vrea să adăugăm și asta, și o hartă pentru a alege locația (în special dacă utilizatorul nu are locația activată la cameră)

**Comment by d-stefan** [comment]
Oh! Credeam că preia adresa de domiciliu deci in contextul ăsta propunerea mea cade. Însă, preluarea coordonatelor din imagine ajuta atunci când faci poza și trimiți sesizarea mai târziu.
